---
driver:
  name: vagrant
  network:
    forwarded_port:
      - guest: 443
        host: 9443
  synced_folders:
    - ['../', '/mnt/source']

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[guardian::default]
    attributes:
      guardian:
        user: vagrant
        group: vagrant
        version: development
