---
driver:
  name: vagrant
  driver:
    network:
      - [forwarded_port, {guest: 443, host: 9443}]
      - [forwarded_port, {guest: 9001, host: 9001}]
      - [forwarded_port, {guest: 9002, host: 9002}]
      - [forwarded_port, {guest: 9003, host: 9003}]
      - [forwarded_port, {guest: 9004, host: 9004}]
  synced_folders:
    - ['../', '/mnt/source']

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[guardian::default]
    attributes:
      guardian:
        user: guardian
        group: guardian
        version: master
